Repository yaito3014/rvariant, pull requests merged in 2025-08, with the labels that each got.

#13 Add GitHub pages deployment
  .github/workflows/deploy_gh_page.yml
  .github/workflows/deploy_gh_page_for_PR.yml
  .gitignore
  doc/rvariant.html
Labels: documentation, CI

#11 Benchmark implementation
  CMakeLists.txt
  include/yk/core/type_traits.hpp
  include/yk/default_init_allocator.hpp
  include/yk/rvariant/detail/rvariant_fwd.hpp
  include/yk/rvariant/detail/variant_storage.hpp
  include/yk/rvariant/detail/visit.hpp
  include/yk/rvariant/rvariant.hpp
  test/CMakeLists.txt
  test/benchmark.cpp
  test/benchmark_support.cpp
  test/benchmark_support.hpp
  test/get_visit_test.cpp
  test/rvariant_test.cpp
  test/rvariant_test.hpp
Labels: documentation, enhancement

#21 Upgrade Clang 19/20 to 21/22
  .github/workflows/run_test.yml
Labels: CI

#27 Add repository links
  README.md
  doc/main.css
  doc/rvariant.adoc
Labels: documentation

#28 Add namespace info
  doc/rvariant.adoc
Labels: documentation

#32 Speed up compilation time
  .clang-tidy
  CMakeLists.txt
  include/yk/core/type_traits.hpp
  include/yk/rvariant/detail/visit.hpp
  include/yk/rvariant/rvariant.hpp
  test/CMakeLists.txt
  test/benchmark.cpp
  test/core_test.cpp
  test/dummy.cpp
  test/many_alternatives_32_test.cpp
  test/rvariant_test.cpp
Labels: enhancement

#34 Add benchmark to the documentation
  doc/rvariant.adoc
  test/benchmark.cpp
Labels: documentation

#35 Add benchmark description
  doc/docinfo.html
  doc/main.css
  doc/rvariant.adoc
Labels: documentation

#36 Remove pointer overloads of `get`
  doc/rvariant.adoc
  include/yk/rvariant/rvariant.hpp
  test/get_visit_test.cpp
Labels: enhancement

#37 Use libc++ in Clang
  .github/workflows/run_test.yml
  CMakeLists.txt
  include/yk/core/type_traits.hpp
Labels: bug, CI

#41 Fix ambiguous syntax on `emplace` with empty args
  include/yk/rvariant/rvariant.hpp
  test/rvariant_test.cpp
Labels: bug

#42 Document supported environments
  README.md
  doc/rvariant.adoc
Labels: documentation

#44 Trigger assertions to detect UB on self-emplace and self-generic-assignment
  include/yk/rvariant/rvariant.hpp
  test/rvariant_test.cpp
Labels: bug, enhancement, language-lawyer

#45 Specify the exact recursive instantiation scenario of atomic constraints on truly recursive types
  doc/rvariant.adoc
  include/yk/core/type_traits.hpp
  include/yk/rvariant/recursive_wrapper.hpp
  include/yk/rvariant/rvariant.hpp
  test/truly_recursive_test.cpp
Labels: documentation, enhancement, truly-recursive

#46 Add `cpp.hint` for Visual Studio
  cpp.hint
Labels: enhancement
